### PR TITLE
Font Formatting for Addresses

### PR DESCRIPTION
**Pull request by masonchain**
Had let this slip into my address validation branch so I reverted the change in this branch.

This is with all upper case Poppins with tabular:
Screen Shot 2022-10-18 at 4 44 00 PM

Regular casing: 
Screen Shot 2022-10-18 at 5 00 01 PM

Roboto Mono:
Screen Shot 2022-10-18 at 4 44 00 PM

### CODE REVIEW

**Comment by nftchance** [comment]
image
image

Honestly, can't even tell a major shift if we change fonts to a nicely monospaced one and it would clean up the dashboard by a significant amount. Going to simmer here but I am considering that we should just update the brand font so that we can remain consistent.

Then, if we ever add on-chain art it can still look good and nice and fit the brand while we only have to upload one font variant which would be ideal.

**Comment by masonchain** [comment]
@nftchance I don't dislike the second one. Not sure what font that one is but I tried fira code that's in the XD on all elements and it definitely changes the entire vibe of the site, but I kinda like it. I defer to whatever font you want to go with but monospace looks like it would work for me.

Fira code:
Screen Shot 2022-10-18 at 4 44 00 PM

**Comment by nftchance** [comment]
Fira is HEAVILY licensed. Will have to find an alt but I'll go searching 🤝

I'd like to make all text on the dashboard smaller anyways so this is perfect.

I will take over this PR from here.

**Comment by nftchance** [comment]
@masonchain Please pull this down and tell me what you think. Closest to Fira that I could find that has flexible licensing.

**Pull request merged**
