### PR TITLE
Delay/Multiple Clicks of Run Transaction Buttons

### PR DESCRIPTION
**Pull request by masonchain**

### CODE REVIEW

**Comment by masonchain** [comment]
https://wagmi.sh/docs/prepare-hooks/intro#ux-pitfalls-without-prepare-hooks

This is the root cause of the issues where someone has to click the button to run a transaction multiple times. The button click did not fail in most cases, but took so long to do the prefetching of transaction parameters (gas, block number, ENS resolving, etc.) that it seems like the click did not work.

With wagmi, you prepare the transaction before-hand so that when the event is fired to run the transaction none of this has to be done and the transaction appears instantly. This raises an issue, however, because the current UX and flow has us pin our IPFS metadata in the same click that runs the transaction. This way we have to await the IPFS response, set it as an arg, and wait for the prepared transaction before the signature appears.

In the linked PR, this issue has been addressed for the Badge management but the Forms are not quite as simple unless we want to be reckless with our IPFS pinning.

The big question is, when do we make the request to pin the metadata if not on the run transaction button? Adding a "Save" button or two clicks of the Create button seems like poor UX but I cannot for the life of me think of a better way to do it aside from firing tens of pin requests as they're editing the form. Adding a Save button to forms for now but if someone please wants to bail me out with a better solution I am all ears.

**Comment by nftchance** [comment]
> but if someone please wants to bail me out with a better solution I am all ears.

Not sure boss. I trust you, you can make whatever decision you know to be best.

**Comment by masonchain** [comment]
ah man this PR got out of scope again. Just need to look into this ipfs hash determination library as a work around for not having a save button and make sure the deterministic hashes are what we actually get from the backend pin. Once that is taken care of (hopefully later tonight) I will merge this PR and open one for smaller bug fixes and another for the rest of the redesign for v5.

**Comment by nftchance** [comment]
Yeah when PRs get so big like this they become blockers and make it difficult for me to  contribute since so many things are changing so often and just creates more work than it's worth.

The PRs are already planned, please just stick to the issues and don't do the entire design update in one or we will be in this situation again

**Pull request merged**
